class CargarDatosVBarras():

    def cargar_datos_ventana_barras(self):
        self.line_edit_diametro_N2.setText(str(
            self.datos_memoria.diametro_N2))
        self.line_edit_area_N2.setText(str(
            self.datos_memoria.area_N2))
        self.line_edit_diametro_N3.setText(str(
            self.datos_memoria.diametro_N3))
        self.line_edit_area_N3.setText(str(
            self.datos_memoria.area_N3))
        self.line_edit_diametro_N4.setText(str(
            self.datos_memoria.diametro_N4))
        self.line_edit_area_N4.setText(str(
            self.datos_memoria.area_N4))
        self.line_edit_diametro_N5.setText(str(
            self.datos_memoria.diametro_N5))
        self.line_edit_area_N5.setText(str(
            self.datos_memoria.area_N5))
        self.line_edit_diametro_N6.setText(str(
            self.datos_memoria.diametro_N6))
        self.line_edit_area_N6.setText(str(
            self.datos_memoria.area_N6))
        self.line_edit_diametro_N7.setText(str(
            self.datos_memoria.diametro_N7))
        self.line_edit_area_N7.setText(str(
            self.datos_memoria.area_N7))
        self.line_edit_diametro_N8.setText(str(
            self.datos_memoria.diametro_N8))
        self.line_edit_area_N8.setText(str(
            self.datos_memoria.area_N8))
        self.line_edit_diametro_N9.setText(str(
            self.datos_memoria.diametro_N9))
        self.line_edit_area_N9.setText(str(
            self.datos_memoria.area_N9))
        self.line_edit_diametro_N10.setText(str(
            self.datos_memoria.diametro_N10))
        self.line_edit_area_N10.setText(str(
            self.datos_memoria.area_N10))
        self.line_edit_diametro_N11.setText(str(
            self.datos_memoria.diametro_N11))
        self.line_edit_area_N11.setText(str(
            self.datos_memoria.area_N11))
        self.line_edit_diametro_N14.setText(str(
            self.datos_memoria.diametro_N14))
        self.line_edit_area_N14.setText(str(
            self.datos_memoria.area_N14))
        self.line_edit_diametro_N18.setText(str(
            self.datos_memoria.diametro_N18))
        self.line_edit_area_N18.setText(str(
            self.datos_memoria.area_N18))
